// <auto-generated />
using System;
using ConsumirApiExterna.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsumirApiExterna.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20250104175220_UpdateRelationUsuarios")]
    partial class UpdateRelationUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsumirApiExterna.Models.Coordinates", b =>
                {
                    b.Property<Guid>("IdCoordinates")
                        .HasColumnType("uuid");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCoordinates");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.DateOfBirth", b =>
                {
                    b.Property<Guid>("IdDateOfBirth")
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDateOfBirth");

                    b.ToTable("DateOfBirths");
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Id", b =>
                {
                    b.Property<Guid>("Idid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Idid");

                    b.ToTable("Ids");
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Location", b =>
                {
                    b.Property<Guid>("IdLocation")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StreetIdStreet")
                        .HasColumnType("uuid");

                    b.HasKey("IdLocation");

                    b.HasIndex("StreetIdStreet");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Login", b =>
                {
                    b.Property<Guid>("IdLogin")
                        .HasColumnType("uuid");

                    b.Property<string>("Md5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sha1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdLogin");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Name", b =>
                {
                    b.Property<Guid>("IdName")
                        .HasColumnType("uuid");

                    b.Property<string>("First")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Last")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdName");

                    b.ToTable("Names");
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Picture", b =>
                {
                    b.Property<Guid>("IdPicture")
                        .HasColumnType("uuid");

                    b.Property<string>("Large")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPicture");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Registered", b =>
                {
                    b.Property<Guid>("IdRegistered")
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRegistered");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Street", b =>
                {
                    b.Property<Guid>("IdStreet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("IdStreet");

                    b.ToTable("Street");
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Timezone", b =>
                {
                    b.Property<Guid>("IdTimezone")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Offset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdTimezone");

                    b.ToTable("Timezone");
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cell")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Coordinates", b =>
                {
                    b.HasOne("ConsumirApiExterna.Models.Location", null)
                        .WithOne("Coordinates")
                        .HasForeignKey("ConsumirApiExterna.Models.Coordinates", "IdCoordinates")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.DateOfBirth", b =>
                {
                    b.HasOne("ConsumirApiExterna.Models.Usuario", null)
                        .WithOne("Dob")
                        .HasForeignKey("ConsumirApiExterna.Models.DateOfBirth", "IdDateOfBirth")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Id", b =>
                {
                    b.HasOne("ConsumirApiExterna.Models.Usuario", null)
                        .WithOne("Id")
                        .HasForeignKey("ConsumirApiExterna.Models.Id", "Idid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Location", b =>
                {
                    b.HasOne("ConsumirApiExterna.Models.Usuario", null)
                        .WithOne("Location")
                        .HasForeignKey("ConsumirApiExterna.Models.Location", "IdLocation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsumirApiExterna.Models.Street", "Street")
                        .WithMany()
                        .HasForeignKey("StreetIdStreet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Street");
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Login", b =>
                {
                    b.HasOne("ConsumirApiExterna.Models.Usuario", null)
                        .WithOne("Login")
                        .HasForeignKey("ConsumirApiExterna.Models.Login", "IdLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Name", b =>
                {
                    b.HasOne("ConsumirApiExterna.Models.Usuario", null)
                        .WithOne("Name")
                        .HasForeignKey("ConsumirApiExterna.Models.Name", "IdName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Picture", b =>
                {
                    b.HasOne("ConsumirApiExterna.Models.Usuario", null)
                        .WithOne("Picture")
                        .HasForeignKey("ConsumirApiExterna.Models.Picture", "IdPicture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Registered", b =>
                {
                    b.HasOne("ConsumirApiExterna.Models.Usuario", null)
                        .WithOne("Registered")
                        .HasForeignKey("ConsumirApiExterna.Models.Registered", "IdRegistered")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Timezone", b =>
                {
                    b.HasOne("ConsumirApiExterna.Models.Location", null)
                        .WithOne("Timezone")
                        .HasForeignKey("ConsumirApiExterna.Models.Timezone", "IdTimezone")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Location", b =>
                {
                    b.Navigation("Coordinates")
                        .IsRequired();

                    b.Navigation("Timezone")
                        .IsRequired();
                });

            modelBuilder.Entity("ConsumirApiExterna.Models.Usuario", b =>
                {
                    b.Navigation("Dob")
                        .IsRequired();

                    b.Navigation("Id")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Login")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Picture")
                        .IsRequired();

                    b.Navigation("Registered")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
